name: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: docker build -t magnumcodus/docker-react -f ./client/Dockerfile.dev .
      # - run: docker run -e CI=true magnumcodus/docker-react npm test -- --coverage

      - run: docker build -t magnumcodus/multi-client ./client
      - run: docker build -t magnumcodus/multi-nginx ./nginx
      - run: docker build -t magnumcodus/multi-server ./server
      - run: docker build -t magnumcodus/multi-worker ./worker
